#ifndef __MainFrm__
#define __MainFrm__

/**
@file
Subclass of MainFrmBase, which is generated by wxFormBuilder.
*/

#include "emberp.h"
#include <string>

//// end generated include

/** Implementing MainFrmBase */
class MainFrm : public MainFrmBase
{
	protected:
		// Handlers for MainFrmBase events.
		void MainFrmClose( wxCloseEvent& event );
		void ValidadeIP( wxCommandEvent& event );
		void ValidadePort( wxCommandEvent& event );
		void ListenBtnPressed( wxCommandEvent& event );
	public:
		/** Constructor */
		MainFrm( wxWindow* parent );
	//// end generated class members
        private:
            std::string ip;
            int port;
};

#endif // __MainFrm__
